### ISSUE TITLE
Have some problems need to be solved

### ISSUE THREAD

**Issue by q145492675** [hvy/chainer-inception-score#1]
Hello, I have followed your guide, and I have some problems need to be solved:
The sceond step: 
  runing :    example.py --model inception_score.model
It returned an error like that:
  File "example.py", line 44, in <module>
         main(args)
  File "example.py", line 25, in main
         cuda.get_device(args.gpu).use()
  File "Cupy/cuda/device.pyx", line 101 , in cupy.cuda.device.Device.use
  File "Cupy/cuda/device.pyx", line 107 , in cupy.cuda.device.Device.use
  File "Cupy\cuda\runtime.pyx", line 185 , in cupy.cuda.runtime.setDevice
  File "Cupy\cuda\runtime.pyx", line 137 , in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidDevice: Invalid device ordinal

Can you help me to solve this problem?

**Comment by q145492675** [comment]
I have solved this problem, Because in my computer, my GPU device number is 0, so I replace your code from example.py line 30: 
               cuda.get_device(args.gpu).use()         to  cuda.get_device_from_id(0).use()    
them this problem has solved, however later I face many new problems: 
One is  "test"  and "valatile" arguments are not suppoted anymore. So I remove all these arguments from your inception_score.py 
    (Eg:  line 42: 
                ims_batch = Variable(ims_batch), volatile=True) to 
                       ims_batch = Variable(ims_batch)#, volatile=True)  )
Them it also has new error like that:
![bed7f79afc7f24aecd50448d9d002e4](https://user-images.githubusercontent.com/32137058/35746660-2621bc48-080d-11e8-8d0a-0650d2e5c09a.png)
Do you know how to solved it?

**Comment by hvy** [comment]
@q145492675 thanks for reporting. The code was not upgraded to the latest Chainer (using `Function`s instead of `FunctionNode`s). It should work now.

**Comment by q145492675** [comment]
Oh I get it, I noticed you have updated your runtime which is adpate to the latest version of Chainer. Now this runtime can work normally in my Python's virtual environment. Thanks a lot~ ^_^

**Comment by hvy** [comment]
Good to hear, I'll close this issue then :)
